"""add admin tables

Revision ID: 3b5cc86365c5
Revises: b9fd9b59b443
Create Date: 2026-03-26 15:45:15.638780

"""
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Sequence, Union

import bcrypt
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5cc86365c5'
down_revision: Union[str, None] = 'b9fd9b59b443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('portal_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('relay_servers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('admin_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed default admin user
    admin_username = os.getenv("ADMIN_USERNAME", "admin")
    admin_password = os.getenv("ADMIN_PASSWORD", "admin")
    password_hash = bcrypt.hashpw(admin_password.encode(), bcrypt.gensalt(12)).decode()

    admin_table = sa.table(
        "admin_users",
        sa.column("username", sa.String),
        sa.column("password_hash", sa.String),
        sa.column("is_active", sa.Boolean),
        sa.column("created_at", sa.DateTime),
    )
    op.bulk_insert(admin_table, [
        {"username": admin_username, "password_hash": password_hash, "is_active": True, "created_at": datetime.utcnow()},
    ])

    # Seed from servers.json if it exists
    for json_path in [Path("config/servers.json"), Path("../config/servers.json")]:
        if json_path.exists():
            with open(json_path) as f:
                data = json.load(f)

            relay_table = sa.table(
                "relay_servers",
                sa.column("id", sa.String),
                sa.column("name", sa.String),
                sa.column("admin_url", sa.String),
                sa.column("api_key", sa.String),
                sa.column("is_active", sa.Boolean),
                sa.column("created_at", sa.DateTime),
                sa.column("updated_at", sa.DateTime),
            )
            now = datetime.utcnow()
            for server in data.get("relay_servers", []):
                op.bulk_insert(relay_table, [{
                    "id": server["id"],
                    "name": server["name"],
                    "admin_url": server["admin_url"],
                    "api_key": server["api_key"],
                    "is_active": True,
                    "created_at": now,
                    "updated_at": now,
                }])

            settings_table = sa.table(
                "portal_settings",
                sa.column("key", sa.String),
                sa.column("value", sa.Text),
                sa.column("updated_at", sa.DateTime),
            )
            portal = data.get("portal", {})
            settings_rows = []
            for k, v in portal.items():
                settings_rows.append({"key": k, "value": str(v), "updated_at": now})
            if settings_rows:
                op.bulk_insert(settings_table, settings_rows)
            break


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relay_servers')
    op.drop_table('portal_settings')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
