"""initial tables

Revision ID: b9fd9b59b443
Revises: 
Create Date: 2026-03-26 13:08:06.157063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fd9b59b443'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_tokens',
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_magic_tokens_email'), 'magic_tokens', ['email'], unique=False)
    op.create_table('portal_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_users_email'), 'portal_users', ['email'], unique=True)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_user_id', sa.String(length=36), nullable=False),
    sa.Column('warning_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_user_id', 'warning_type', name='uq_user_warning')
    )
    op.create_table('server_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_user_id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=50), nullable=False),
    sa.Column('server_name', sa.String(length=100), nullable=False),
    sa.Column('smtp_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('mail_domain', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'smtp_user_id', name='uq_server_smtp_user')
    )
    op.create_table('warning_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_user_id', sa.String(length=36), nullable=False),
    sa.Column('warning_type', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warning_log')
    op.drop_table('server_accounts')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_portal_users_email'), table_name='portal_users')
    op.drop_table('portal_users')
    op.drop_index(op.f('ix_magic_tokens_email'), table_name='magic_tokens')
    op.drop_table('magic_tokens')
    # ### end Alembic commands ###
